info:
  profile: default

server:
  port: 8702 # 服务提供方

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8699/eureka
  instance:
    hostname: localhost

#当前服务名称
spring:
  application:
    name: eureka-service1

from:
  GitConfigService1-3.0